enum TypeInferrer:
  case Auto
  case StringType
  case FromTuple[T]()
  case FromTupled
end TypeInferrer

enum HeaderOptions {
  case AutoGenerated
  case Manual(headers: String*)
  case FromRows(merge: Int, dropFirst: Int = 0)
}
