//> using scala 3.7.2

import scala.quoted.*

@main def call =
  println("x")
  import scala.quoted.*
  val x1 = mac(HeaderOptions.AutoGenerated, TypeInferrer.Auto)
  val x2 =
    mac(HeaderOptions.AutoGenerated, TypeInferrer.FromTuple[(Int, Int)]())
  val x3 = overload1(TypeInferrer.FromTuple[(Int, Int)]())
  println(x1)
  println(x2)
  println(x3)
